


DELETE  http://localhost:4000/subscribers/61c44f9cbf8eec4735f2a3ff

###

# POST http://localhost:4000/subscribers
# Content-Type:application/json

# {
#     "name":"thisis",
#     "subscribedToChannel":"webde"
# }